apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
        - name: Go-challenge-container
          image:ibrahimayman1997/Go-challenge
          resources:
            limits:
              memory: "150Mi"
              cpu: "700m"
          ports:
            - containerPort: 8080